### ISSUE TITLE
Bug with False Positive Identification

### ISSUE THREAD

**Issue by crg-n** [lowe-lab-ucl/unet_segmentation_metrics#2]
Hi, first thanks for the great tool. Seems to be designed to do exactly what I'm looking to do!

However, I think there is some sort of odd bug with the False Positive detection. I attach an example excerpt of some segmentations:

<img src="https://user-images.githubusercontent.com/23727785/113722971-cf558700-96e8-11eb-9b7f-7b45fefe88e9.png" data-canonical-src="https://user-images.githubusercontent.com/23727785/113722971-cf558700-96e8-11eb-9b7f-7b45fefe88e9.png" width="350"/>

As you can see the initial segmentation has some small spotty detections in the top right that aren't in the ground truth. This seems to show up in the segmentation metrics with n_true_labels 32 and n_pred_labels 40, however n_false_positives is only 2. Running area_opening to remove these as shown below and then re-running umetrics correctly reduces the number of predicted labels bringing it closer to the number of true labels but the false positives don't change and nor does the Jaccard index. I am correctly passing the ground to umetrics.calculate first and then the prediction second. Interestingly swapping them around seems to make things work as expected but they are incorrectly called false negatives etc.

Any idea what's going on here?

Many thanks,
Craig

**Comment by quantumjot** [comment]
Hi @crgnclsn - thanks for this report. Seems like we should really add some tests ;) Do you want to help?

**Comment by SabraHashemi** [comment]
is this bug solved?
could you explain when this happen totally?

**Comment by quantumjot** [comment]
I think this bug should be fixed now. LMK if you end up trying it
